baseURL = "http://wazatoki.github.io/"
languageCode = "ja-jp"
title = "scribbling block"
theme = "mainroad"
publishDir = "docs"

hasCJKLanguage = true # 日本語・中国語・韓国語の単語カウントを有効にする
summaryLength = 120 # サマリーの長さを120単語にする